import Head from "next/head";
import React, { useContext } from "react";
import { Col, Container, Hidden } from "react-grid-system";
import BottomNav from "../BottomNav";

export default function index({ children }) {
    return (
        <>
            <Head>
                <title>Wedding Lembo & Ani</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/l-a.icon.png" />
                <meta httpEquiv="Content-Type" content="text/html; charset=UTF-8" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1, maximum-scale=1"
                />
                <meta name="robots" content="max-image-preview:large" />
            </Head>
            <div id="fb-root"></div>
            <script async defer crossOrigin="anonymous" src="https://connect.facebook.net/id_ID/sdk.js#xfbml=1&version=v14.0&appId=230102141039057&autoLogAppEvents=1" nonce="FWad5VrJ"></script>
            {children}
        </>
    );
}
